get works for grade and set grade to work
urfuProject2022/StudentEstimateServiceApi pull request #11
Opened 2022-05-07 14:39 UTC by qqqqqq452

2022-05-10 19:01 UTC, ALyalin22 requested changes

2022-05-10 19:01 UTC, ALyalin22 commented on Models/DTO/SetGradeDto.cs
> +        [FromHeader]
А для чего передавать информацию в заголовках? Почему не сделать в теле самого запроса?

2022-05-10 19:01 UTC, ALyalin22 commented on Infrastructure/GradeService/GradeService.cs
> +                return OperationResult.Fail("Assignment expired");
Думаю не нужно ограничивать оценивание работ после дедлайна

2022-05-10 19:01 UTC, ALyalin22 commented on Infrastructure/Services/WorkService/WorkService.cs
> +                return OperationResult.Fail("Assignment expired");
Та же история, лучше не ограничивать оценку после дедлайна

2022-05-10 19:01 UTC, ALyalin22 commented on Infrastructure/Services/WorkService/WorkService.cs
> +            var gradedWorksCount = gradeRepository.GetGradesSettedByUser(user, dto.Assignment);
Можно вынести gradedWorksCount в поле модели studentGradeInfo, и увеличивать его когда ставишь оценку кому-либо. (Если я конечно правильно понял смысл модели studentGradeInfo)

2022-05-13 13:30 UTC, qqqqqq452 commented on Models/DTO/SetGradeDto.cs
> +        [FromHeader]
Да, в теле будет лучше, поправил

2022-05-13 13:30 UTC, qqqqqq452 commented on Infrastructure/GradeService/GradeService.cs
> +                return OperationResult.Fail("Assignment expired");
Поправил

2022-05-13 13:30 UTC, qqqqqq452 commented on Infrastructure/Services/WorkService/WorkService.cs
> +                return OperationResult.Fail("Assignment expired");
Поправил

2022-05-13 13:31 UTC, qqqqqq452 commented on Infrastructure/Services/WorkService/WorkService.cs
> +            var gradedWorksCount = gradeRepository.GetGradesSettedByUser(user, dto.Assignment);
studentGradeInfo связывает сколько работ должен оценить студент в рамках задания. 
>Можно вынести gradedWorksCount в поле модели

А в чем плюсы такого решения?:)
На данный момент при оценивании работы у нас обновляется сущность работы и создается сущность оценки, но если мы вынесем gradedWorksCount  в модельку studentGradeInfo, то тогда при проставлении оценки придется трогать 3 сущности и всегда помнить что нужно обновнить счетчик оцененных работ, кажется что это не очень хорошо, потому что мы будем хранить инфу которая у нас уже есть(пройтись по бд) и всегда нужно будет помнить что необходимо обновлять помимо работы еще  и studentGradeInfo, что может казаться не очевидным

2022-05-14 11:49 UTC, ALyalin22 approved these changes

2022-05-14 11:49 UTC, ALyalin22 commented on Infrastructure/Services/WorkService/WorkService.cs
> +            var gradedWorksCount = gradeRepository.GetGradesSettedByUser(user, dto.Assignment);
В целом да, согласен, так лучше будет. Меня просто смутило, что каждый раз нужно будет проходиться по всем работам, чтобы найти сколько работ оценил юзер. На больших данных это может быть затратно, хотя если правильно настроить индексы в монге, то всё должно быть ок

2022-05-14 11:50 UTC, merged